---
title: 'Project 2: Modeling, Testing, and Predicting'
author: "Caroline Cweren, cc63235"
date: '5/1/20'
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
---



<p>#Caroline Cweren, cc63235</p>
<div id="modeling" class="section level1">
<h1>Modeling</h1>
<div id="instructions" class="section level2">
<h2>Instructions</h2>
<p>A knitted R Markdown document (as a PDF) and the raw R Markdown file (as .Rmd) should both be submitted to Canvas by 11:59pm on 5/1/2020. These two documents will be graded jointly, so they must be consistent (i.e., don’t change the R Markdown file without also updating the knitted document). Knit an html copy too, for later! In the .Rmd file for Project 2, you can copy the first code-chunk into your project .Rmd file to get better formatting. Notice that you can adjust the opts_chunk$set(…) above to set certain parameters if necessary to make the knitting cleaner (you can globally set the size of all plots, etc). You can copy the set-up chunk in Project2.Rmd: I have gone ahead and set a few for you (such as disabling warnings and package-loading messges when knitting)!</p>
<p>Like before, I envision your written text forming something of a narrative structure around your code/output. All results presented must have corresponding code. Any answers/results/plots etc. given without the corresponding R code that generated the result will not be graded. Furthermore, all code contained in your final project document should work properly. Please do not include any extraneous code or code which produces error messages. (Code which produces warnings is acceptable, as long as you understand what the warnings mean).</p>
</div>
<div id="find-data" class="section level2">
<h2>Find data:</h2>
<p>Find one dataset with at least 5 variables that wish to use to build models. At least one should be categorical (with 2-5 groups) and at least two should be numeric. Ideally, one of your variables will be binary (if not, you will need to create one by discretizing a numeric, which is workable but less than ideal). You will need a minimum of 40 observations (<em>at least</em> 10 observations for every explanatory variable you have, ideally 20+ observations/variable).</p>
<p>It is perfectly fine to use either dataset (or the merged dataset, or a subset of your variables) from Project 1. However, you could also diversify your portfolio a bit by choosing a different dataset to work with (particularly if the variables did not reveal interesting associations in Project 1). The only requirement/restriction is that you may not use data from any examples we have done in class or lab. It would be a good idea to pick more cohesive data this time around (i.e., variables that you actually thing might have a relationship you would want to test). Think more along the lines of your Biostats project.</p>
<p>Again, you can use data from anywhere you want (see bottom for resources)! If you want a quick way to see whether a built-in (R) dataset has binary and/or character (i.e., categorical) variables, check out this list: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
</div>
<div id="guidelines-and-rubric" class="section level2">
<h2>Guidelines and Rubric</h2>
<ul>
<li><p><strong>0. (5 pts)</strong> Introduce your dataset and each of your variables (or just your main variables if you have lots) in a paragraph. What are they measuring? How many observations?</p></li>
<li><p><strong>1. (15 pts)</strong> Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all doesn’t make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find response(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which groups differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss assumptions and whether or not they are likely to have been met (2).</p></li>
<li><p><strong>2. (10 pts)</strong> Perform some kind of randomization test on your data (that makes sense). This can be anything you want! State null and alternative hypotheses, perform the test, and interpret the results (7). Create a plot visualizing the null distribution and the test statistic (3).</p></li>
<li><p><strong>3. (35 pts)</strong> Build a linear regression model predicting one of your response variables from at least 2 other variables, including their interaction. Mean-center any numeric variables involved in the interaction.</p>
<ul>
<li>Interpret the coefficient estimates (do not discuss significance) (10)</li>
<li>Plot the regression using <code>ggplot()</code>. If your interaction is numeric by numeric, refer to code near the end of WS15 to make the plot. If you have 3 or more predictors, just chose two to plot for convenience. (8)</li>
<li>Check assumptions of linearity, normality, and homoskedasticity either graphically or using a hypothesis test (4)</li>
<li>Regardless, recompute regression results with robust standard errors via <code>coeftest(..., vcov=vcovHC(...))</code>. Discuss significance of results, including any changes from before/after robust SEs if applicable. (8)</li>
<li>What proportion of the variation in the outcome does your model explain? (4)</li>
</ul></li>
<li><p><strong>4. (5 pts)</strong> Rerun same regression model (with interaction), but this time compute bootstrapped standard errors. Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)</p></li>
<li><p><strong>5. (40 pts)</strong> Perform a logistic regression predicting a binary categorical variable (if you don’t have one, make/get one) from at least two explanatory variables (interaction not necessary).</p>
<ul>
<li>Interpret coefficient estimates in context (10)</li>
<li>Report a confusion matrix for your logistic regression (2)</li>
<li>Compute and discuss the Accuracy, Sensitivity (TPR), Specificity (TNR), and Recall (PPV) of your model (5)</li>
<li>Using ggplot, plot density of log-odds (logit) by your binary outcome variable (3)</li>
<li>Generate an ROC curve (plot) and calculate AUC (either manually or with a package); interpret (10)</li>
<li>Perform 10-fold (or repeated random sub-sampling) CV and report average out-of-sample Accuracy, Sensitivity, and Recall (10)</li>
</ul></li>
<li><p><strong>6. (10 pts)</strong> Choose one variable you want to predict (can be one you used from before; either binary or continuous) and run a LASSO regression inputting all the rest of your variables as predictors. Choose lambda to give the simplest model whose accuracy is near that of the best (i.e., <code>lambda.1se</code>). Discuss which variables are retained. Perform 10-fold CV using this model: if response in binary, compare model’s out-of-sample accuracy to that of your logistic regression in part 5; if response is numeric, compare the residual standard error (at the bottom of the summary output, aka RMSE): lower is better fit!</p></li>
</ul>
</div>
<div id="where-do-i-find-data-again" class="section level2">
<h2>Where do I find data again?</h2>
<p>You can choose ANY datasets you want that meet the above criteria for variables and observations. You can make it as serious as you want, or not, but keep in mind that you will be incorporating this project into a portfolio webpage for your final in this course, so choose something that really reflects who you are, or something that you feel will advance you in the direction you hope to move career-wise, or something that you think is really neat, or whatever. On the flip side, regardless of what you pick, you will be performing all the same tasks, so it doesn’t end up being that big of a deal.</p>
<p>If you are totally clueless and have no direction at all, log into the server and type</p>
<pre class="r"><code>data(package = .packages(all.available = TRUE))</code></pre>
<p>This will print out a list of <strong>ALL datasets in ALL packages</strong> installed on the server (a ton)! Scroll until your eyes bleed! Actually, do not scroll that much… To start with something more manageable, just run the command on your own computer, or just run <code>data()</code> to bring up the datasets in your current environment. To read more about a dataset, do <code>?packagename::datasetname</code>.</p>
<p>If it is easier for you, and in case you don’t have many packages installed, a list of R datasets from a few common packages (also downloadable in CSV format) is given at the following website: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
<ul>
<li><p>A good package to download for fun/relevant data is <code>fivethiryeight</code>.
Run <code>install.packages(&quot;fivethirtyeight&quot;),</code> load the packages with <code>library(fivethirtyeight)</code>, run <code>data()</code>, and then scroll down to view the datasets. Here is an online list of all 127 datasets (with links to the 538 articles). Lots of sports, politics, current events, etc.</p></li>
<li><p>If you have already started to specialize (e.g., ecology, epidemiology) you might look at discipline-specific R packages (vegan, epi, respectively). We will be using some tools from these packages later in the course, but they come with lots of data too, which you can explore according to the directions above</p></li>
<li><p>However, you <em>emphatically DO NOT</em> have to use datasets available via R packages! In fact, I would much prefer it if you found the data from completely separate sources and brought them together (a much more realistic experience in the real world)! You can even reuse data from your SDS328M project, provided it shares a variable in common with other data which allows you to merge the two together (e.g., if you still had the timestamp, you could look up the weather that day: <a href="https://www.wunderground.com/history/" class="uri">https://www.wunderground.com/history/</a>). If you work in a research lab or have access to old data, you could potentially merge it with new data from your lab!</p></li>
<li><p>Here is a curated list of interesting datasets (read-only spreadsheet format): <a href="https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit" class="uri">https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit</a></p></li>
<li><p>Here is another great compilation of datasets: <a href="https://github.com/rfordatascience/tidytuesday" class="uri">https://github.com/rfordatascience/tidytuesday</a></p></li>
<li><p>Here is the UCI Machine Learning Repository: <a href="https://archive.ics.uci.edu/ml/index.php" class="uri">https://archive.ics.uci.edu/ml/index.php</a></p>
<ul>
<li>See also <a href="https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data" class="uri">https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data</a></li>
</ul></li>
<li><p>Here is another good general place to look: <a href="https://www.kaggle.com/datasets" class="uri">https://www.kaggle.com/datasets</a></p></li>
<li><p>To help narrow your search down or to see interesting variable ideas, check out <a href="https://www.tylervigen.com/spurious-correlations" class="uri">https://www.tylervigen.com/spurious-correlations</a>. This is the spurious correlations website, and it is fun, but if you look at the bottom of each plot you will see sources for the data. This is a good place to find very general data (or at least get a sense of where you can scrape data together from)!</p></li>
<li><p>If you are interested in medical data, check out www.countyhealthrankings.org</p></li>
<li><p>If you are interested in scraping UT data, they make <em>loads</em> of data public (e.g., beyond just professor CVs and syllabi). Check out all the data that is available in the statistical handbooks: <a href="https://reports.utexas.edu/statistical-handbook" class="uri">https://reports.utexas.edu/statistical-handbook</a></p></li>
</ul>
<div id="broader-data-sources" class="section level5">
<h5>Broader data sources:</h5>
<p><a href="www.data.gov">Data.gov</a> 186,000+ datasets!</p>
<p><a href="Social%20Explorer">Social Explorer</a> is a nice interface to Census and American Community Survey data (more user-friendly than the government sites). May need to sign up for a free trial.</p>
<p><a href="www.bls.gov">U.S. Bureau of Labor Statistics</a></p>
<p><a href="www.census.gov">U.S. Census Bureau</a></p>
<p><a href="www.gapminder.org/data">Gapminder</a>, data about the world.</p>
<pre class="r"><code>#0
library(dplyr)
library(ggplot2)
mydata &lt;- read.csv(&quot;Leinhardt.csv&quot;)
mydata&lt;-na.omit(mydata)</code></pre>
<p>The dataset I chose is named “Leinhardt”and contains important data in order to explain infant mortality. The dataset contains 105 observations and 4 variables, including infant, income, region, and oil. The variable income is a numeric variable measuring the per-capita income in U.S. dollars. The variable infant is a numeric variable measuring the infant-mortality rate per every 1000 live births. The variable region is a categorical variable that consists of 4 various regions of the world, including Africa,Asia, Americas, and Europe. Lastly, the variable oil was a binary categorical variable. This variable described whether the region was in an oil-exporting country by separating data into categories of “yes” or “no”.</p>
<pre class="r"><code>#1
library(tidyverse)
manov1&lt;-manova(cbind(infant,income)~region, data=mydata)
summary(manov1)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## region 3 0.58638 13.412 6 194 1.056e-12 ***
## Residuals 97
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(manov1)</code></pre>
<pre><code>## Response infant :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## region 3 210752 70251 11.103 2.494e-06 ***
## Residuals 97 613743 6327
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response income :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## region 3 96029824 32009941 28.207 3.362e-13 ***
## Residuals 97 110076893 1134813
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>pairwise.t.test(mydata$infant, mydata$region, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  mydata$infant and mydata$region 
## 
##          Africa  Americas Asia   
## Americas 0.00012 -        -      
## Asia     0.02676 0.07550  -      
## Europe   7.1e-07 0.15918  0.00199
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(mydata$income, mydata$region, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  mydata$income and mydata$region 
## 
##          Africa  Americas Asia   
## Americas 0.017   -        -      
## Asia     0.166   0.296    -      
## Europe   3.0e-14 2.3e-08  6.2e-11
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>1-(0.95)^15</code></pre>
<pre><code>## [1] 0.5367088</code></pre>
<pre class="r"><code>0.05/15</code></pre>
<pre><code>## [1] 0.003333333</code></pre>
<p>The MANOVA tested the effect of the categorical variable, region, with four region categories of Africa, Americas, Europe, and Asia on two numeric variables income and infant(infant mortality rate).The probability of at least one type 1 error was 0.5367. Based on the bonferroni method, the adjusted significance level was 0.003. The MANOVA revealed that at least one of the numeric variables, infant and income, showed a significant mean difference across regions. Thus, two univariate ANOVAs were performed in order to determine which numeric variable had a significant mean difference across the 4 regions. The ANOVA test revealed that both infant and income numeric variables had significant differences. As a result, post-hoc analysis conducted 6 pairwise comparisons to determine which region differed in the infant variable. Another post-hoc analysis conducted 6 pairwise comparison to determine which region differed in income. After adjusting for multiple comparisons (bonferroni), pariwise t.test comparisons that showed a significant difference between regions for the infant variable were Africa/Europe, Africa/America, and Asia/Europe.The comparisons of regions that still contained a significant difference for the income variable after adjusting for multiple comparisons were Africa/Europe, Europe/America, and Asia and Europe.The MANOVA assumptions are random sampling/independent observations, multivariate normality of dependent variables,linear relationships among dependent variables, homogeneity of within-group covariance matrices, no extreme univariate or multivariate outliers, and no multicollinearity. All of these were likely to have been met except for the outliers assumptions.The no extreme univariate or multivariate outliers assumption was violated due to the presence of outliers.</p>
<pre class="r"><code>#2
library(vegan)
mydata%&gt;%group_by(oil)%&gt;%summarize(mean_income=mean(income))</code></pre>
<pre><code>## # A tibble: 2 x 2
##   oil   mean_income
##   &lt;fct&gt;       &lt;dbl&gt;
## 1 no          1032.
## 2 yes          915</code></pre>
<pre class="r"><code>rand_dist&lt;-vector()
for(i in 1:5000){
  new&lt;-data.frame(income=sample(mydata$income),oil=mydata$oil)
rand_dist[i]&lt;-mean(new[new$oil==&quot;yes&quot;,]$income)-mean(new[new$oil==&quot;no&quot;,]$income)
}
mydata%&gt;%group_by(oil)%&gt;%summarize(means=mean(income))%&gt;%summarize(`mean_diff:`=diff(means))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   `mean_diff:`
##          &lt;dbl&gt;
## 1        -117.</code></pre>
<pre class="r"><code>{hist(rand_dist,main=&quot;&quot;,ylab=&quot;&quot;);abline(v=-116.57,col=&quot;red&quot;)}</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>mean(rand_dist&gt;116.57)*2</code></pre>
<pre><code>## [1] 0.7592</code></pre>
<pre class="r"><code>mean(rand_dist&gt;116.57| rand_dist&lt; -116.57)</code></pre>
<pre><code>## [1] 0.8218</code></pre>
<p>Null Hypothesis: Mean income is the same for countries that export oil and countries that do not export oil.
Alternative Hypothesis: Mean income is different for countries that export oil and countries that do not export oil.
The p-value from the randomization test was 0.834, which is insignificant. Thus, we fail to reject the null hypothesis and it can be concluded that the mean income is the same for countries that export oil and countries that do not.</p>
<pre class="r"><code>#3

mydata&lt;-mydata%&gt;%mutate(income_c=scale(mydata$income, center=TRUE, scale=FALSE))
fit&lt;-lm(infant~region*income_c, data=mydata)
summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = infant ~ region * income_c, data = mydata)
##
## Residuals:
## Min 1Q Median 3Q Max
## -101.04 -31.36 -2.58 16.25 559.77
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 173.47392 24.43724 7.099 2.46e-10 ***
## regionAmericas -118.78086 29.78589 -3.988 0.000133 ***
## regionAsia -79.78997 29.42574 -2.712 0.007977 **
## regionEurope -143.99763 41.08788 -3.505 0.000705 ***
## income_c 0.04163 0.02702 1.541 0.126827
## regionAmericas:income_c -0.05133 0.02982 -1.721 0.088578
.
## regionAsia:income_c -0.04842 0.03121 -1.552 0.124155
## regionEurope:income_c -0.04669 0.03018 -1.547 0.125292
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 79.83 on 93 degrees of freedom
## Multiple R-squared: 0.2811, Adjusted R-squared: 0.227
## F-statistic: 5.194 on 7 and 93 DF, p-value: 5.055e-05</code></pre>
<pre class="r"><code>newdat&lt;-mydata
newdat$region&lt;-rep(&quot;Asia&quot;,length(newdat$region))
newdat$pred1&lt;-predict(fit,newdat)
newdat$region&lt;-rep(&quot;Americas&quot;, length(newdat$region))
newdat$pred2&lt;-predict(fit,newdat)
newdat$region&lt;-rep(&quot;Europe&quot;, length(newdat$region))
newdat$pred3&lt;-predict(fit,newdat)
newdat$region&lt;-rep(&quot;Africa&quot;, length(newdat$region))
newdat$pred4&lt;-predict(fit,newdat)
ggplot(mydata,aes(x=income_c, y=infant))+geom_point()+geom_line(data=newdat,aes(y= newdat$pred1),color=&#39;red&#39;)+geom_line(data=newdat,aes(y=newdat$pred2), color=&#39;blue&#39;) + geom_line(data=newdat, aes(y=pred3), color=&#39;green&#39;)+geom_line(data=newdat, aes(y=pred4), color=&#39;purple&#39;)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-5-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>resids&lt;-fit$residuals
f_values&lt;-fit$fitted.values
ggplot()+geom_point(aes(f_values,resids))+geom_hline(yintercept=0, col=&quot;red&quot;)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-5-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot()+geom_histogram(aes(resids), bins=30)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-5-3.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>shapiro.test(resids)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resids
## W = 0.62903, p-value = 1.332e-14</code></pre>
<pre class="r"><code>library(sandwich)
library(lmtest)
bptest(fit)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 7.3663, df = 7, p-value = 0.3918</code></pre>
<pre class="r"><code>summary(fit)$coef[,1:2]</code></pre>
<pre><code>##                              Estimate  Std. Error
## (Intercept)              173.47391999 24.43724157
## regionAmericas          -118.78086302 29.78589117
## regionAsia               -79.78997344 29.42573871
## regionEurope            -143.99762955 41.08788003
## income_c                   0.04162687  0.02702112
## regionAmericas:income_c   -0.05132790  0.02982465
## regionAsia:income_c       -0.04842307  0.03120856
## regionEurope:income_c     -0.04669194  0.03018487</code></pre>
<pre class="r"><code>coeftest(fit,vcov=vcovHC(fit))[,1:2]</code></pre>
<pre><code>##                              Estimate  Std. Error
## (Intercept)              173.47391999 103.5492624
## regionAmericas          -118.78086302 103.7377723
## regionAsia               -79.78997344 109.0305481
## regionEurope            -143.99762955 103.6808772
## income_c                   0.04162687   0.1223717
## regionAmericas:income_c   -0.05132790   0.1223973
## regionAsia:income_c       -0.04842307   0.1251815
## regionEurope:income_c     -0.04669194   0.1223872</code></pre>
<pre class="r"><code>summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = infant ~ region * income_c, data = mydata)
##
## Residuals:
## Min 1Q Median 3Q Max
## -101.04 -31.36 -2.58 16.25 559.77
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 173.47392 24.43724 7.099 2.46e-10 ***
## regionAmericas -118.78086 29.78589 -3.988 0.000133 ***
## regionAsia -79.78997 29.42574 -2.712 0.007977 **
## regionEurope -143.99763 41.08788 -3.505 0.000705 ***
## income_c 0.04163 0.02702 1.541 0.126827
## regionAmericas:income_c -0.05133 0.02982 -1.721 0.088578
.
## regionAsia:income_c -0.04842 0.03121 -1.552 0.124155
## regionEurope:income_c -0.04669 0.03018 -1.547 0.125292
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 79.83 on 93 degrees of freedom
## Multiple R-squared: 0.2811, Adjusted R-squared: 0.227
## F-statistic: 5.194 on 7 and 93 DF, p-value: 5.055e-05</code></pre>
<p>A linear regression model was performed to predict infant(infant mortality rate) based on the interaction of region and income_c.The full model of the interaction is infant=173.47-118.78(regionAmericas)-79.79(regionAsia)-143.997(regionEurope)+0.042(income-c)-.051(regionAmericas:income_c)-.048(regionAsia:income_c)-0.047(regionEurope:income_c).Controlling for income_c, when regionAmericas is 1 and the other region levels are 0, “infant”&quot; decreases by a factor of 118.78. Controlling for income_c, when regionAsia is 1 and the other regions levels are 0, infant decreases by a factor of 79.79. Controlling for income_c, when regionEurope is 1 and the other regions levels are 0, infant decreases by a factor of -143.997.For every 1-unit increase in income_c, infant increases by a factor of 0.042 on average. For the interaction, when regionAmericas is 1 and the other region levels are 0, the resulting equation is infant = 54.69 - 0.01(income_c). For the interaction, when regionAsia is 1 and the other region levels are 0, the resulting equation is infant = 93.68-0.006(income_c). For the interaction, when regionEurope is 1 and the other region levels are 0, the resulting equation is infant = 29.47-0.005(income_c). The estimate for the interaction term is the difference in the slopes. After the assumptions were checked, the data was shown to be heteroskedastic. Since the data was not homoskedatic, robust standard errors for the regression results were computed to correct the standard errors. The significance of the results showed that there was a change from the uncorrected SEs to the robust SEs, revealing that the data did violate the homoskedastic assumption. The uncorrected SEs for the predictors mostly increased in value after computing for robust SEs. The proportion of variation in the response variable, infant (mortality rate),explained by the model or all predictors at once is the R^2 value of 0.227.</p>
<pre class="r"><code>#4
bptest(fit)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 7.3663, df = 7, p-value = 0.3918</code></pre>
<pre class="r"><code>library(dplyr)
x=seq(-5,5,length.out=1000)
y=1+2*x+rnorm(1000)
dat&lt;-data.frame(x,y)
boot_dat&lt;-sample_frac((dat),replace=T)

samp_distn&lt;-replicate(5000, {
 boot_dat&lt;-sample_frac(mydata,replace=T)
 fit&lt;-lm(infant~region*income_c,data=boot_dat)
 coef(fit)
 })
samp_distn%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>## (Intercept) regionAmericas regionAsia regionEurope
income_c regionAmericas:income_c
## 1 58.72757 59.08488 78.8191 58.82514 0.06822296
0.06868568
## regionAsia:income_c regionEurope:income_c
## 1 0.0899319 0.0682836</code></pre>
<p>The bootstrapped SEs were determined usign the regression model with the interaction. The bootstrapped SEs were then compared to the regular SEs and the robust SEs. The bootstrapped SEs were generally very different values and much larger than the regular SEs. The robust SEs and the bootstrapped SEs were also different. The robust SEs were also larger than the bootstrapped SEs. The p-value for the interaction model was 0.3918, which is insignificant.</p>
<pre class="r"><code>#5

fit1&lt;-glm(oil~ region + infant,data=mydata,family=&quot;binomial&quot;)
coeftest(fit1)</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -3.2439e+00 8.0415e-01 -4.0339 5.486e-05 ***
## regionAmericas 5.9168e-01 1.0135e+00 0.5838 0.55936
## regionAsia 3.2163e-01 9.1256e-01 0.3524 0.72450
## regionEurope -1.6440e+01 2.5337e+03 -0.0065 0.99482
## infant 6.0628e-03 3.3416e-03 1.8143 0.06963 .
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coef(fit1))</code></pre>
<pre><code>## (Intercept) regionAmericas regionAsia regionEurope
infant
## 3.901233e-02 1.807023e+00 1.379376e+00 7.246927e-08
1.006081e+00</code></pre>
<pre class="r"><code>prob&lt;-predict(fit1,type=&quot;response&quot;)
pred&lt;-ifelse(prob&gt;.5,1,0)

table(truth=mydata$oil,prediction=pred)%&gt;%addmargins</code></pre>
<pre><code>##      prediction
## truth   0   1 Sum
##   no   93   0  93
##   yes   7   1   8
##   Sum 100   1 101</code></pre>
<pre class="r"><code>(1+93)/101 #accuracy</code></pre>
<pre><code>## [1] 0.9306931</code></pre>
<pre class="r"><code>1/8 #tpr</code></pre>
<pre><code>## [1] 0.125</code></pre>
<pre class="r"><code>93/100 #tnr</code></pre>
<pre><code>## [1] 0.93</code></pre>
<pre class="r"><code>1/1 #ppv</code></pre>
<pre><code>## [1] 1</code></pre>
<pre class="r"><code>odds&lt;-function(p)p/(1-p) 
p&lt;-seq(0,1,by=.1)
cbind(p, odds=odds(p))%&gt;%round(4)</code></pre>
<pre><code>##         p   odds
##  [1,] 0.0 0.0000
##  [2,] 0.1 0.1111
##  [3,] 0.2 0.2500
##  [4,] 0.3 0.4286
##  [5,] 0.4 0.6667
##  [6,] 0.5 1.0000
##  [7,] 0.6 1.5000
##  [8,] 0.7 2.3333
##  [9,] 0.8 4.0000
## [10,] 0.9 9.0000
## [11,] 1.0    Inf</code></pre>
<pre class="r"><code>logit&lt;-function(p)log(odds(p))
cbind(p, odds=odds(p),logit=logit(p))%&gt;%round(4)</code></pre>
<pre><code>##         p   odds   logit
##  [1,] 0.0 0.0000    -Inf
##  [2,] 0.1 0.1111 -2.1972
##  [3,] 0.2 0.2500 -1.3863
##  [4,] 0.3 0.4286 -0.8473
##  [5,] 0.4 0.6667 -0.4055
##  [6,] 0.5 1.0000  0.0000
##  [7,] 0.6 1.5000  0.4055
##  [8,] 0.7 2.3333  0.8473
##  [9,] 0.8 4.0000  1.3863
## [10,] 0.9 9.0000  2.1972
## [11,] 1.0    Inf     Inf</code></pre>
<pre class="r"><code>mydata$logit&lt;-predict(fit1)
mydata%&gt;%ggplot()+geom_density(aes(logit, color=oil, fill= oil),alpha = .3)+geom_vline(xintercept=0, lty=2)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-7-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(plotROC) 
data(mydata)%&gt;%head()</code></pre>
<pre><code>## [1] &quot;mydata&quot;</code></pre>
<pre class="r"><code>mydata_omit&lt;- mydata %&gt;% na.omit()
fit1&lt;-glm(oil~ region +infant,data=mydata,family=&quot;binomial&quot;)
prob3&lt;-predict(fit1,type=&quot;response&quot;)
ROCplot&lt;-ggplot(mydata_omit)+geom_roc(aes(d=oil,m=prob3), n.cuts=0)
ROCplot</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-7-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.6626344</code></pre>
<pre class="r"><code>class_diag &lt;- function(probs,truth){
  

  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]

  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
  
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

  data.frame(acc,sens,spec,ppv,auc)
}
set.seed(1234)
k=10
data1&lt;-mydata[sample(nrow(mydata)),] 
folds&lt;-cut(seq(1:nrow(mydata)),breaks=k,labels=F) 

diags&lt;-NULL
  for(i in 1:k){
 train&lt;-data1[folds!=i,]
 test&lt;-data1[folds==i,]
 truth&lt;-test$oil
 fit&lt;-glm(oil~infant+region,data=train,family=&quot;binomial&quot;)
 probs&lt;-predict(fit,newdata = test,type=&quot;response&quot;)
 diags&lt;-rbind(diags,class_diag(probs,truth))
}
apply(diags,2,mean)</code></pre>
<pre><code>##       acc      sens      spec       ppv       auc 
## 0.9118182       NaN 0.9900000       NaN 0.3444444</code></pre>
<p>A logistic regression was performed predicting the binary categorical variable, oil, from the explanatory variables known as income and infant.Controlling for regionAfrica, regionAmericas, regionAsia, and regionEurope do not have a signicant effect on the log-odds of oil(oil=1). The odds of progression observed for regionAmerica are 5.92e-1 times that of Africa. Controlling for region, odds of progression observed are not significantly affected by infant. A confusion matrix was performed for the logistic regresission to plot model predictions against true values. The proportion of correctly classified cases is the overall accuracy and was computed to be 0.93. The proportion of observed progressions correctly classified is the sensitivity (TPR) and was determined to be 0.125. The proportion of censored progressions (no progression observed, oil = 0) correctly classified is the specificity (TNR) and was computed to be 0.93. The proportion of those classified as observed progressions who actually are is the precision (PPV) and was computed to be 1. An ROC curve showed the area under the curve (AUC) which determines how well the predictions are overall. The AUC computed from the ROCplot was 0.6626. The calculated AUC is considered poor based on the fact that it lies between 0.6 and 0.7. The 10-fold CV was performed and generated an average out-of-sample accuracy value of 0.9309, which indicates that the model is a good predictor of oil-exporting counties and not oil-exporting countries. The average out of sample sensitivity was 0, and the average out of sample recall was 0.</p>
<pre class="r"><code>#6
library(glmnet)
fit2 &lt;- glm(oil ~ -1 + income + infant + region, data = mydata_omit, family = &quot;binomial&quot;)
model.matrix(fit2) %&gt;% head()</code></pre>
<pre><code>## income infant regionAfrica regionAmericas regionAsia
regionEurope
## 1 3426 26.7 0 0 1 0
## 2 3350 23.7 0 0 0 1
## 3 3346 17.0 0 0 0 1
## 4 4751 16.8 0 1 0 0
## 5 5029 13.5 0 0 0 1
## 6 3312 10.1 0 0 0 1</code></pre>
<pre class="r"><code>set.seed(1234)
x&lt;-model.matrix(fit2)
x&lt;-scale(x)
y&lt;-as.matrix(mydata_omit$oil)
cv&lt;-cv.glmnet(x,y,family=&#39;binomial&#39;)
lasso&lt;-glmnet(x,y,family=&#39;binomial&#39;,lambda=0.0498)
coef(lasso)</code></pre>
<pre><code>## 7 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                        s0
## (Intercept)    -2.4796799
## income          .        
## infant          0.2363576
## regionAfrica    .        
## regionAmericas  .        
## regionAsia      .        
## regionEurope    .</code></pre>
<pre class="r"><code>mydata_omit$Asia&lt;-ifelse(mydata$region==&quot;Asia&quot;,1,0)
set.seed(1234)
k=10
data1&lt;-mydata_omit[sample(nrow(mydata_omit)),]
folds&lt;-cut(seq(1:nrow(mydata)),breaks=k,labels=F)
diags&lt;-NULL
for(i in 1:k){
train&lt;-data1[folds!=i,]
test&lt;-data1[folds==i,]
truth&lt;-test$oil 
fit3&lt;-glm(oil~  infant,data=train,family=&quot;binomial&quot;) 
probs&lt;-predict(fit3,newdata = test,type=&quot;response&quot;) 
diags&lt;-rbind(diags,class_diag(probs,truth))
}
diags%&gt;%summarize_all(mean)</code></pre>
<pre><code>##         acc sens spec ppv       auc
## 1 0.9218182  NaN    1 NaN 0.4277778</code></pre>
<pre class="r"><code>plot(cv$glmnet.fit,&quot;lambda&quot;)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-8-1.png" width="768" style="display: block; margin: auto;" />
A lasso regression was performed predicting the binary categorical variable, oil (oil-exporting countries=1 and not oil-exporting countries=0), with all the other variables as predictors. Lambda was chosen to give the simplest model with accuracy near the best. From the lasso, the only variable that was retained was infant, indicating that infant mortality rate is an important predictor of the oil binary categorical variable. Based on the 10-fold CV using the model, the out-of-sample accuracy was 0.9309, which is almost the same as the out-of-sample accuracy of 0.9309 from logistic regression in part 5. Based in the high accuracy value, it can be concluded that the model was an overall good predictor of distinguishing between countries that export oil and countries that do not export oil. The high accuracing indicated a high proportion of correctly classified cases. However, the AUC of 0.293, which is a very bad AUC, was much lower than the AUC of 0.6626 found in the logistic regression of part 5.</p>
<p>…</p>
</div>
</div>
</div>
